### ISSUE TITLE
Couldn't make it work with xmllint-action

### ISSUE THREAD

**Issue by vitalyk-multinarity** [korelstar/xmllint-problem-matcher#4]
Hi,
I've tried to use this action according to xmllint-action readme, but I didn't see annotated output, just the same output as before.

```
    - uses: korelstar/xmllint-problem-matcher@v1
    - name: Lint ROM manifest
       uses: ChristophWurst/xmllint-action@v1 
       with:
         xml-file:my-manifest.xml
         xml-schema-file: my-schema.xsd
```

Any suggestions?

Thank you,
Vitaly
