### ISSUE TITLE
Option for failed workflow

### ISSUE THREAD

**Issue by LangLangBart** [korelstar/xmllint-problem-matcher#5]
Hi, I am using your workflow to validate some xml files in my repo. I wonder if you can answer me one question.
How do I set up the workflow to fail if a single warning or error comes up?

**Comment by korelstar** [comment]
Hey @LangLangBart,
if you run `xmllint` in your workflow, the workflow run should fail if there are errors. This behavior is independent of the `xmllint-problem-matcher`.

If you want to have an example, please look at [this workflow](https://github.com/nextcloud/notes/blob/master/.github/workflows/lint.yml) (the job `lint-xml` uses `xmllint-problem-matcher` and runs `make lint-xml`) and [this Makefile](https://github.com/nextcloud/notes/blob/master/Makefile) (the task `lint-xml` runs `xmllint`).

Does this help?

**Comment by LangLangBart** [comment]
Hello @korelstar, thanks for the reply.

I have created a workflow to illustrate the problem.

#### Workflow
```yml
# Test workflow setup
# https://github.com/korelstar/xmllint-problem-matcher/issues/5
---
name: XML test

on:
  push:
    branches:
      - test_XML
  workflow_dispatch:

jobs:
  test_XML:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      # Validate the XML schema for gui files
      - name: Download rng
        run: |
          wget https://raw.githubusercontent.com/0ad/0ad/master/binaries/data/mods/mod/gui/gui.rng
      - name: Install xmllint
        run: |
          sudo apt update
          sudo apt install --no-install-recommends -y libxml2-utils
      - name: Setup xmllint problem matcher
        # https://github.com/korelstar/xmllint-problem-matcher
        uses: korelstar/xmllint-problem-matcher@master
      - name: Validate gui XML
        run: find ./gui -name '*.xml' -mindepth 1 -exec xmllint --relaxng ./gui.rng --noout {} \;
```

#### success
After the workflow is executed, it will be completed with `success`. See Logout below.
```zsh
❯ gh run watch
? Select a workflow run * test setup, XML test (test_XML) 2s ago
✓ test_XML XML test · 2778492194
Triggered via push less than a minute ago

JOBS
✓ test_XML in 17s (ID 7621693378)
  ✓ Set up job
  ✓ Check out repository
  ✓ Download rng
  ✓ Install xmllint
  ✓ Setup xmllint problem matcher
  ✓ Validate gui XML
  ✓ Post Check out repository
  ✓ Complete job

✓ Run XML test (2778492194) completed with 'success'
```

#### ANNOTATIONS
When checking for `ANNOTATIONS`, an error is correctly listed. See logout below.
```zsh
❯ gh run view
? Select a workflow run ✓ test setup, XML test (test_XML) 43s ago

✓ test_XML XML test · 2778492194
Triggered via push less than a minute ago

JOBS
✓ test_XML in 17s (ID 7621693378)

ANNOTATIONS
X Did not expect element page there
test_XML: gui/page_session.xml#2


For more information about the job, try: gh run view --job=7621693378
View this run on GitHub: https://github.com/LangLangBart/boonGUI/actions/runs/2778492194
```

> Does this help?

Yes, i had another look at your setup and made the following change to one command

```diff
--- a/.github/workflows/code_quality.yml
+++ b/.github/workflows/code_quality.yml
@@ -29,4 +29,4 @@ jobs:
         # https://github.com/korelstar/xmllint-problem-matcher
         uses: korelstar/xmllint-problem-matcher@master
       - name: Validate gui XML
-        run: find ./gui -name '*.xml' -mindepth 1 -exec xmllint --relaxng ./gui.rng --noout {} \;
+        run: for f in $(find ./gui -name '*.xml' -mindepth 1); do xmllint "$f" --relaxng ./gui.rng --noout; done
```

#### failure
After that change the workflow ends (correctly) with `failure`. This is the outcome I was looking for.

```zsh
❯ gh run watch
? Select a workflow run * test setup with loop, XML test (test_XML) 2s ago
X test_XML XML test · 2778560015
Triggered via push less than a minute ago

JOBS
X test_XML in 15s (ID 7621865333)
  ✓ Set up job
  ✓ Check out repository
  ✓ Download rng
  ✓ Install xmllint
  ✓ Setup xmllint problem matcher
  X Validate gui XML
  ✓ Post Check out repository
  ✓ Complete job

X Run XML test (2778560015) completed with 'failure'
```

Do you know why the `loop` works and the option with `-exec` does not?

PS: The issue can be closed, the workaround with the loop works.
